# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

  # desc "Install cocoapods"
  # lane :install_pods do
  #   cocoapods(
  #       clean: true,
  #       use_bundle_exec: false
  # )
  # end
  desc "Archive ipa"
  lane :archive do
    # cocoapods(repo_update: true)
    cocoapods(
        clean: true,
        use_bundle_exec: false
    )
    xcodebuild(
      archive: true,
      archive_path: "./build-dir/CICDDemo.xcarchive",
      scheme: "CICDDemo",
      workspace: "CICDDemo.xcworkspace",
      destination: "generic/platform=iOS",
      xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO"
    )
    zip(
      path: "./build-dir/CICDDemo.xcarchive",
      output_path: "./build-dir/CICDDemo.xcarchive.zip"
    )
end
