name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 11 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Pod install
        run: pod install
      - name: Build
        run: |
          xcodebuild clean build -project CICDDemo.xcodeproj -scheme CICDDemo -destination "platform=iOS Simulator,name=iPhone 11 Pro" CODE _SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
          destination: ${{ matrix.destination }}

      - name: Test
        run: |
          xcodebuild clean test -project CICDDemo.xcodeproj -scheme CICDDemo -destination "platform=iOS Simulator,name=iPhone 11 Pro" CODE _SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
          destination: ${{ matrix.destination }}
