name: iOS starter workflow Alt

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Dependencies
        run: pod install --repo-update
        shell: bash
      - name: Build
        run: |
          pod install --repo-update && xcodebuild clean build -project CICDDemo.xcodeproj -scheme CICDDemo -destination "platform=iOS Simulator,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Test
        run: |
          xcodebuild clean test -project CICDDemo.xcodeproj -scheme CICDDemo -destination "platform=iOS Simulator,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO